### PR TITLE
Sync with Block Starter repo

### LINKED ISSUE #9: Replace wdsbs with {{ textdomain }}
This is great stuff. Thanks for all the hard work you've put into this. 👍 

One note on the current placeholders in the templates.

In [lib/templates/wds/src/block/rich-text/index.js.mustache](https://github.com/WebDevStudios/create-block/blob/6b68afdf81ca1bd5743fecf565455102f79494c3/lib/templates/wds/src/block/rich-text/index.js.mustache#L22) I think the text domain `wdsbs` should be replaced with `{{ textdomain }}` (the same value we use for the text domain in [lib/templates/wds/%24slug.php.mustache](https://github.com/WebDevStudios/create-block/blob/master/lib/templates/wds/%24slug.php.mustache#L17))

I think this same replacement also comes up in other templates.

### LINKED ISSUE #10: Sync with latest WDS/Block-Starter files
While developing `v2` which pulls the latest files from WDS/Block-Starter repo on-demand, i'll have to manually update the template files here.

### PR DESCRIPTION
**Pull request by donmhico**
Closes #10, closes #9 

### DESCRIPTION ###
This PR updates the **template files** to sync with `WebDevStudios/wds-block-starter` repo. 

### SCREENSHOTS ###
The following screenshots are from generated plugin block starter after running the command.

**Plugin files**
SS 1

**Plugin Dashboard**
SS 2

**Inside editor**
SS 3

**Frontend**
SS 4

### STEPS TO VERIFY ###
1. Clone this PR.
2. Inside the cloned directory run `npm install` then `npm run create-block WebDevStudios/TodoBlock`.
3. After running the command above, you'll have a new folder named `todo-block`. Copy that to a WordPress `wp-content/plugins`.
4. Test the generated plugin and confirm it works.

### CODE REVIEW

**Review by gregrickaby — COMMENTED** [review]
@donmhico I get an error with Node LTS 12.14.1:

```bash
➜  create-block git:(issue/10-Sync-with-WDS-Block-Starter-repo) npm run create-block WebDevStudios/TodoBlock

> @webdevstudios/create-block@0.0.4 create-block /Users/gregoryrickaby/Local/create-block
> node index.js "WebDevStudios/TodoBlock"

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'inquirer'
Require stack:
- /Users/gregoryrickaby/Local/create-block/lib/index.js
- /Users/gregoryrickaby/Local/create-block/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gregoryrickaby/Local/create-block/lib/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/gregoryrickaby/Local/create-block/lib/index.js',
    '/Users/gregoryrickaby/Local/create-block/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @webdevstudios/create-block@0.0.4 create-block: `node index.js "WebDevStudios/TodoBlock"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @webdevstudios/create-block@0.0.4 create-block script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gregoryrickaby/.npm/_logs/2020-04-03T12_43_48_524Z-debug.log
```

**Comment by donmhico** [comment]
@gregrickaby  Sorry, forgot to mention to run `npm install` before `npm run create-block WebDevStudios/TodoBlock`

**Comment by gregrickaby** [comment]
@donmhico It works...however I have some feedback.

I generated a "To Do" block, but what I got was a "Rich Text" block. So, when I went to look for the block in the WP dashboard, I searched for "to do" and "wds" and nothing came up. It wasn't until I looked at your screenshot above, that I saw a "rich text" block was generated.

If someone runs `npm run create-block WebDevStudios/TodoBlock` the generator should name the block what I used in the namespace, so I can find it.

**Review by gregrickaby — APPROVED** [review]
Approving. We're going to create a new issue about customizing the block based on Namespace.

**Pull request merged**
